# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_support.ipynb.

# %% ../nbs/01_support.ipynb #f9f96c81
"Probe and install kernel support into a project's Python environment."

# %% ../nbs/01_support.ipynb #65533c0a
from __future__ import annotations

# %% auto #0
__all__ = ['HOST_PY', 'INSPECTOR', 'INSPECTOR_TTL', 'KERNEL_PACKAGES', 'IMPORT_FAULTS', 'work_dir', 'support_paths',
           'kernel_support', 'inspector_support', 'import_failure', 'installable', 'as_installed',
           'install_kernel_support', 'install_inspector_support']

# %% ../nbs/01_support.ipynb #f4b7e620
import os, shutil, subprocess, sys, threading, time

# %% ../nbs/01_support.ipynb #68962790
from pathlib import Path

# %% ../nbs/01_support.ipynb #dedc3092
#: This interpreter's minor version. A kernel may borrow this `sys.path` only when it matches.
HOST_PY = tuple(sys.version_info[:2])

# %% ../nbs/01_support.ipynb #f361168d
INSPECTOR, INSPECTOR_TTL = ('dhrishti',), 90
KERNEL_PACKAGES = ('ipykernel', 'ipymini', 'kernmini', 'fastcore', 'microio')

# %% ../nbs/01_support.ipynb #e11cebe4
_INSPECT = {}

# %% ../nbs/01_support.ipynb #e3107ad3
_locks, _locks_lock = {}, threading.Lock()

# %% ../nbs/01_support.ipynb #1cb69b65
from .pythons import BUNDLE_ONLY, clean_env, strip_bundle

# %% ../nbs/01_support.ipynb #5663cd06
def work_dir(cwd=None):
    "`cwd` as a string, falling back to a writable directory when the process inherited `/` or a read-only bundle."
    if cwd: return str(cwd)
    here = os.getcwd()
    if not getattr(sys, 'frozen', False): return here
    return here if here != os.sep and os.access(here, os.W_OK) else str(Path.home())

# %% ../nbs/01_support.ipynb #5a5c78c4
def support_paths():
    "The `sys.path` entries `bootstrap_src` hands a kernel to borrow from."
    return [p for p in sys.path if p and os.path.isabs(p) and os.path.exists(p)]

# %% ../nbs/01_support.ipynb #e6710d46
def _lock_for(python):
    "One lock per interpreter: two installers in one venv is a race, and three surfaces offer it."
    with _locks_lock: return _locks.setdefault(str(python), threading.Lock())

# %% ../nbs/01_support.ipynb #ef6fb62c
class _Failed:
    "What a command that never started looks like, so a probe reports instead of raising."
    returncode, stdout = 127, ''
    def __init__(self, err): self.stderr = err

def _run(args, timeout=180):
    "Run a command and return its result; missing interpreter and timeout are returned as answers, not raised."
    try:
        return subprocess.run([str(x) for x in args], env=clean_env(), text=True,
            encoding='utf-8', errors='replace', capture_output=True, timeout=timeout)
    except subprocess.TimeoutExpired: return _Failed(f'timed out after {timeout}s')
    except OSError as e: return _Failed(str(e))

# %% ../nbs/01_support.ipynb #8df48f16
def _last_line(text):
    "The line a traceback ends on. numpy's ABI failure wraps its own in eighteen lines of advice."
    return next((l for l in reversed((text or '').strip().splitlines()) if l.strip()), '').strip()

# %% ../nbs/01_support.ipynb #d2641692
def _probe(python, module, paths=()):
    "Whether `module` imports in `python`, with its version or the failure."
    pre = (f'import sys\nif tuple(sys.version_info[:2]) == {HOST_PY!r}: '
           f'sys.path.extend({list(paths)!r})\n') if paths else ''
    p = _run([python, '-c', f'{pre}import {module}; print(getattr({module}, "__version__", "installed"))'], 15)
    return {'available': p.returncode == 0,
        'version': p.stdout.strip() if p.returncode == 0 else '',
        'error': _last_line(p.stderr or p.stdout) if p.returncode else ''}

# %% ../nbs/01_support.ipynb #b2ac2073
def kernel_support(python):
    "Importability of both supported kernel launchers in ``python``."
    python = str(Path(python).expanduser())
    return {m: _probe(python, m) for m in ('ipykernel', 'ipymini')}

# %% ../nbs/01_support.ipynb #96fb5abf
def inspector_support(python, refresh=False):
    "Check whether `python` can import the live-variable inspector, returning what blocked it if not."
    python = str(Path(python).expanduser())
    hit = _INSPECT.get(python)
    if not refresh and hit and time.time() - hit[0] < INSPECTOR_TTL: return hit[1]
    state = _probe(python, 'dhrishti.serving', support_paths())
    _INSPECT[python] = (time.time(), state)
    return state

IMPORT_FAULTS = ('ModuleNotFoundError', 'ImportError', 'No module named')

def import_failure(err):
    "Whether bootstrap failed on an inspector import."
    return any(s in (err or '') for s in IMPORT_FAULTS)

# %% ../nbs/01_support.ipynb #fdd325b4
def installable(python):
    "Whether anything may install into `python`. Never this one, and never inside a signed bundle."
    if not python: return False
    p = os.path.abspath(str(python))
    if p == os.path.abspath(sys.executable): return False
    return '/Contents/Resources/' not in p and '/Contents/MacOS/' not in p

# %% ../nbs/01_support.ipynb #a9657e48
def as_installed(names=KERNEL_PACKAGES):
    "Pin `names` to the versions this process runs; leave unpinned what it doesn't have, so installs stay compatible with the host."
    from importlib.metadata import PackageNotFoundError, version
    out = []
    for name in names:
        try: out.append(f'{name}=={version(name)}')
        except (PackageNotFoundError, ValueError, OSError): out.append(name)
    return out

# %% ../nbs/01_support.ipynb #45ff1680
def _attempts(python, packages):
    "Installer commands to try, in order, for environments that intentionally lack pip."
    out = []
    if uv := shutil.which('uv'): out.append([uv, 'pip', 'install', '--python', python, *packages])
    out.append([python, '-m', 'pip', 'install', *packages])
    if not uv and _run([python, '-m', 'ensurepip', '--upgrade']).returncode == 0:
        out.insert(0, [python, '-m', 'pip', 'install', *packages])
    return out

# %% ../nbs/01_support.ipynb #2dd32fe7
def _log(command, p): return {'command': command, 'returncode': p.returncode,'output': (p.stdout + '\n' + p.stderr).strip()[-8000:]}
def _detail(logs): return next((a['output'] for a in reversed(logs) if a['output']), 'no installer answered')

# %% ../nbs/01_support.ipynb #c4af38c4
def install_kernel_support(python, packages=None):
    "Install kernel packages via uv or pip; verify the import works after, so failures name the package not the installer."
    python = str(Path(python).expanduser().absolute())
    packages, logs, unimportable = list(packages or as_installed()), [], ''
    with _lock_for(python):
        for command in _attempts(python, packages):
            p = _run(command, 600)
            logs.append(_log(command, p))
            if p.returncode == 0:
                support = kernel_support(python)
                if all(x['available'] for x in support.values()): return {'ok': True, 'python': python, 'support': support, 'attempts': logs}
                unimportable = '; '.join(f"{name} installed but does not import ({x['error']})" for name, x in support.items() if not x['available'])
    raise RuntimeError(f'kernel support installation failed: {unimportable or _detail(logs)}')

# %% ../nbs/01_support.ipynb #4ce3e0ba
def install_inspector_support(python, packages=INSPECTOR):
    "Give `python` its own copy of what the inspector imports, then ask it again."
    python = str(Path(python).expanduser().absolute())
    logs = []
    with _lock_for(python):
        for command in _attempts(python, packages):
            p = _run(command, 600)
            logs.append(_log(command, p))
            if p.returncode != 0: continue
            state = inspector_support(python, refresh=True)
            if state['available']: return {'ok': True, 'python': python, 'inspector': state, 'attempts': logs}
            raise RuntimeError(f'{" and ".join(packages)} are installed, and the inspector still will not import: {state["error"]}')
    raise RuntimeError(f'could not install {" and ".join(packages)}: {_detail(logs)}')
